fitur_3/urls.py
from django.conf.urls import url
from .views import index, add_message, dashboard

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message/', add_message, name='add_message'),
	url(r'^dashboard/(?P<pengguna>.*)/$', dashboard, name='dashboard'),


]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import fitur_1.urls as fitur_1
import fitur_2.urls as fitur_2
import fitur_3.urls as fitur_3
import fitur_4.urls as fitur_4


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^fitur-1/', include(fitur_1, namespace='fitur-1')),
    url(r'^fitur-2/', include(fitur_2,namespace='fitur-2')),
    url(r'^fitur-3/', include(fitur_3,namespace='fitur-3')),
	url(r'^fitur-4/', include(fitur_4,namespace='fitur-4')),
	url(r'^$', RedirectView.as_view(url='fitur-1/'))
]

fitur_3/models.py
from django.db import models

class Message(models.Model):
	pengguna = models.CharField(max_length=100, null=True, default='not-set')
	title = models.CharField(max_length=140, null=True, default='not-set')
	message = models.TextField(null=True)
	created_date = models.DateTimeField(auto_now_add=True, null=True)

	# , default='not-set', unique=True

fitur_3/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    title_attrs = {
        'class': 'form-control',
        'placeholder':'This post is about...'
    }

    message_attrs = {
        'class': 'form-control',
        'placeholder':'Your post is...'
    }

    title = forms.CharField(label='Judul Forum', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=message_attrs), required=True)

fitur_3/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Message_Form
from .models import Message

# Create your views here.

response = {}
# hahah

def index(request):
	response['author']= "Widya Syafira"
	html = 'fitur_3/fitur_3.html'
	return HttpResponseRedirect('/fitur-3/dashboard/13601373')
	#return render(request, html, response)

def dashboard(request, pengguna):
    message = Message.objects.filter(pengguna=pengguna)
   
    response['message'] = message
    response['message_form'] = Message_Form
    response["message_list"] = message
    # print("kkkkkk"+ str(message))
    html = 'fitur_3/fitur_3.html'

    message_list = message
    paginator = Paginator(message_list, 5)
    page = request.GET.get('page', 1)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
   
    response["message_list"] = users
    html = 'fitur_3/fitur_3.html'
    return render(request, html, response)


def add_message(request):
	form = Message_Form(None or request.POST )

	if (request.method == 'POST' and form.is_valid()):
		response['pengguna'] = 13101373
		response['title'] = request.POST['title'] 
		response['message'] = request.POST['message']
		message = Message(pengguna=13601373,title= response['title'], message= response['message'])
		message.save()
		html ='fitur_3/fitur_3.html'    
		return HttpResponseRedirect('/fitur-3/')
	else :
		return HttpResponseRedirect('/fitur-3/')

def paginate_page(page, data_list):

	paginator = Paginator(data_list, 5)

	try:
		data = paginator.page(page)
	except PageNotAnInteger:
		data = paginator.page(1)
	except EmptyPage:
		data = paginator.page(paginator.num_pages)

	# Get the index of the current page
	index = data.number - 1
	# This value is maximum index of your pages, so the last page - 1
	max_index = len(paginator.page_range)
	# You want a range of 10, so lets calculate where to slice the list
	start_index = index if index >= 5 else 0
	end_index = 5 if index < max_index - 5 else max_index
	# Get our new page range. In the latest versions of Django page_range returns 
	# an iterator. Thus pass it to list, to make our slice possible again.
	page_range = list(paginator.page_range)[start_index:end_index]
	paginate_data = {'data':data, 'page_range':page_range}
	return paginate_data

fitur_3/templates/fitur_3/fitur_3.html
{% extends "fitur_3/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<div class="jumbotron jumbotron-fluid text-center" style="margin-bottom: 0px; margin-top: 0px; background-color: #F1F7ED">
  <div class="container">
    <img class="rounded-circle" src="https://image.ibb.co/d7BEZb/forum.png" alt="Generic placeholder image" style="width:270px;height:175px;">
    <h1 class="display-3" style="font-family: Impact;">Forum Diskusi Lowongan</h1>
    <h4 class="lead" style="fontfamily: Lucida">find jobs here</h4>
  </div>
</div>

<section name="form">
    <h2>Send Message</h2>
    <div class="list-group">
        {% if message_list %}
             
            {% for i in message_list %}
                <a class="list-group-item clearfix"> 
                    {{i.title}} - {{i.message}} - {{i.created_date}} 
                </a>        
            {% endfor %}
      
        {% else %}
            <button type="submit" class="btn btn-primary btn-lg btn-block no-friend">You have no discussion.</button>
        {% endif %}
    </div>
    <form id="form" method="POST" action="{% url 'fitur-3:add_message'  %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>

    {% if message_list.has_other_pages %}
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</section>

<!-- <div class="list-group">
    {% if message_list %}
         
        {% for i in message_list %}
            <a class="list-group-item clearfix"> 
                {{i.title}} - {{i.message}} - {{i.created_date}} 
            </a>        
        {% endfor %}
  
    {% else %}
        <button type="submit" class="btn btn-primary btn-lg btn-block no-friend">You have no discussion.</button>
    {% endif %}
</div>
 -->

<!--  PAGINATION
{% if message_list.has_other_pages %}
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %} -->
{% endblock %}