fitur_1/urls.py
from django.conf.urls import url
from .views import index, add_session, remove_session

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-session/$', add_session, name='add-session'),
	url(r'^remove-session/$', remove_session, name='remove-session'),
]

fitur_4/urls.py
from django.conf.urls import url
from .views import add_tanggapan

urlpatterns = [
 	url(r'add_tanggapan/$', add_tanggapan, name='add_tanggapan'),
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import fitur_1.urls as fitur_1
import fitur_2.urls as fitur_2
import fitur_3.urls as fitur_3
import fitur_4.urls as fitur_4


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^fitur-1/', include(fitur_1, namespace='fitur-1')),
    url(r'^fitur-2/', include(fitur_2,namespace='fitur-2')),
    url(r'^fitur-3/', include(fitur_3,namespace='fitur-3')),
	url(r'^fitur-4/', include(fitur_4,namespace='fitur-4')),
	url(r'^$', RedirectView.as_view(url='fitur-1/'))
]

templates/tugas2/partials/header.html
<style>
/*========================================== INI BUAT NAVBAR, COPAS YANG INI YA ============================================= */
/*========================================== INI BUAT NAVBAR, COPAS YANG INI YA ============================================= */
/*========================================== INI BUAT NAVBAR, COPAS YANG INI YA ============================================= */
/*========================================== INI BUAT NAVBAR, COPAS YANG INI YA ============================================= */
body{
    margin-top: 70px;
    font-family: 'Cabin', sans-serif;
}

nav{
    text-transform: uppercase;
    font-weight: bold;
    letter-spacing: 4px;
}

.navbar-default {
    background-color: #fafafa;
    border:none;
}

/* LINK COLOUR LMAOOOO*/
.navbar-default .navbar-nav > li > a {
    color:#f1c40f;
    text-decoration: none;
}

.navbar-default .navbar-brand{
    color: #9b59b6;
    text-decoration: none;
}

.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus, .navbar-default .navbar-nav > li > a:active {
    color: #9b59b6;
    text-decoration: none;
}

ul a {
    position: relative;
    display: block;
    padding: 16px 0;
    margin: 0 12px;
    line-height: 16px;
    transition: color 0.1s,background-color 0.3s,padding 0.2s ease-in;
}
ul a::before {
    content: '';
    display: block;
    position: absolute;
    bottom: 3px;
    left: 0;
    height: 3px;
    width: 100%;
    background-color: #9b59b6;  /*UNDERLINES COLOUR*/
    transform-origin: right top;
    transform: scale(0, 1);
    transition: color 0.1s,transform 0.3s ease-out;
}
ul a:active::before {
    background-color: #9b59b6;
}
ul a:hover::before, ul a:focus::before {
    transform-origin: left top;
    transform: scale(1, 1);
}

/* ===================================================== NAVBAR DONE HERE ==========================================================*/
/* ===================================================== NAVBAR DONE HERE ==========================================================*/
/* ===================================================== NAVBAR DONE HERE ==========================================================*/
/* ===================================================== NAVBAR DONE HERE ==========================================================*/

</style>


<nav class="navbar navbar-toggleable-md navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"> PPWC-10 </a>
    </div>
    <div id="navbar-collapse" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navigation-list">
        <li><a href="{% url 'fitur-1:index' %}">Home</a></li>
        <li><a href="{% url 'fitur-4:add_tanggapan' %}">Tanggapan</a></li>
      </ul>
    </div>
  </div>