fitur_2/urls.py
from django.conf.urls import url
from .views import index, add_company

urlpatterns = [
    url(r'^(?P<id>\d+)/$', index, name='index'),
    url(r'^add-company/$',add_company, name='add-company')
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import fitur_1.urls as fitur_1
import fitur_2.urls as fitur_2
import fitur_3.urls as fitur_3
import fitur_4.urls as fitur_4


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^fitur-1/', include(fitur_1, namespace='fitur-1')),
    url(r'^fitur-2/', include(fitur_2,namespace='fitur-2')),
    url(r'^fitur-3/', include(fitur_3,namespace='fitur-3')),
	url(r'^fitur-4/', include(fitur_4,namespace='fitur-4')),
	url(r'^$', RedirectView.as_view(url='fitur-1/'))
]

fitur_2/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    
    id = models.CharField(max_length=400, primary_key=True, default='not-set')
    name = models.CharField(max_length=400, null=True, default='not-set')
    desc = models.CharField(max_length=500, default='not-set', null=True)
    companyType = models.CharField(max_length=100, default='not-set', null=True)
    website = models.URLField(null=True)
    specialities = models.CharField(max_length=100, default='not-set', null=True)
    address = models.CharField(max_length=100, default='not-set', null=True)

fitur_2/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Company
import os
import json

response = {}

def index(request, id):
    response['login'] = True
    company = Company.objects.get(id__exact=id)
    response['name'] = company.name
    response['com_type'] = company.companyType
    response['website'] = company.website
    response['desc'] = company.desc
    response['specialities'] = company.specialities
    response['address'] = company.address
    # print("desc "+company.desc)
    # print("jadiii " + company.name)
    html = 'fitur_2/fitur_2.html/'
    return render(request, html, response)

@csrf_exempt
def add_company(request):
    id = request.POST.get('id')
    print(request.POST)
    print("comtype "+request.POST.get('specialties[values][]'))
    if (Company.objects.filter(id__exact=id).count()> 0):
        company = Company.objects.get(id__exact=id)
        company.desc = request.POST.get('description')
        company.companyType = request.POST.get('companyType[name]')
        company.website = request.POST.get('websiteUrl')
        company.desc = request.POST.get('description')
        company.specialities = request.POST.get('specialties[values][]')
        company.address = request.POST.get('locations[values][0][address][street1]')
    
        company.save()
        return HttpResponse(id)

    name = request.POST.get('name')
    com_type = request.POST.get('companyType[name]')
    website = request.POST.get('websiteUrl')
    desc = request.POST.get('description')
    specialities = request.POST.get('specialties[values][]')
    address = request.POST.get('locations[values][0][address][street1]')
    company = Company(id=id, name=name,companyType=com_type,website=website,desc=desc,address=address,specialities=specialities)
    company.save()
    return HttpResponse(id)

fitur_2/templates/fitur_2/fitur_2.html
{% extends "fitur_2/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/onepage-scroll.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/component.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_2.css' %}" />
</head>
<div class="wrapper">
 <div class="main">
    <section class="page1">
       <div class="page_container">
          <div id="home">
            <div class="this-is">
              THIS IS
            </div>
            <div class="get-name">
              {{ name }}
            </div>

            <div class="buttons">
              <a href="{% url 'fitur-3:index' %}" class="ghost-button">Lihat Forum</a>
              <a href="#" class="ghost-button">Cari Mahasiswa</a>
            </div>
          </div>
     </div>
    </section>

    <section class="page2">
      <div class="page_container">
         <div id="about">
            <div class="about-label section-title">
               |About
            </div>
            <div class="about-content">
              <div class="pic-name">
                  <div id="get-pic">
                     <img src='{{ logo_url }}'>
                  </div>
              </div>
              <div class="about-text">
                  <div class="get-name">
                     {{ name }}
                  </div>
                  <div class="get-company-type">
                    a {{ com_type }} company
                  </div>
                  <div class="description">
                    {{ desc }}
                  </div>
              </div>
            </div>
         </div>
      </div>
    </section>

    <section class="page3">
       <div class="page_container">
          <div id="specialities">
            <div class="specialities-label section-title">
               |Specialities
            </div>
            <div class="specialities-container">
              {{specialities}}
            </div>
         </div>
      </div>
    </section>

    <section class="page4">
      <div class="page_container section-title">
        <div id="contact">
          <div class="contact-label section-title">
            |Contact
          </div>
          <div class="contact-container">
            <div class="visit-label">
              MEET US AT
            </div>
            <div class="loc">
              <img src="https://cdn.iconscout.com/public/images/icon/premium/png-512/company-adress-office-location-3b83c14ad48950c8-512x512.png">
            </div>
            <div class="address">
              {{ address }}
            </div>
            <div class="visit-label">
              OR VISIT OUR WEBSITE
            </div>
            <a class="ghost-button" href="#">{{ website }}</a>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<script src="https://code.jquery.com/jquery-2.1.4.js" integrity="sha256-siFczlgw4jULnUICcdm9gjQPZkw/YPDqhQ9+nAOScE4=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/jquery.onepage-scroll.js' %}"></script>
<script src="{% static 'js/fitur_2.js' %}"></script>
<script type="text/javascript">
    $(document).ready(() => {
        $(".navigation-list").append(
            '<li><a onClick="logout()">Logout</a></li>'
        )
    })
</script>
{% endblock %}